### ISSUE TITLE
Love this script - cron+email

### ISSUE THREAD

**Issue by txcanyon** [tavinus/opkg-upgrade#1]
Masterful work. I wonder if it is possible to have it email you when there are updates. For example say I set a cron job to check for updates every Friday. Instead of sshing into the box and running your script manually, it could email me the list of update-able packages.

**Comment by tavinus** [comment]
Hi! Interesting idea.  
I have no experience on mailing from OpenWRT/LEDE, do you currently use one of the solutions available?  
  
[From this article](https://wiki.openwrt.org/doc/howto/smtp.client), our choices seem to be:
 - msmtp
 - mailsend
 - ssmtp

All of them would have options with or without SSL.  
  
Seems a bit tricky to include the mailer into opkg-upgrade.  
It would probably be easier to just create flags to *`check`* and *`list`*.  
  
So the user can configure whatever mailer they want and use something like this:
```
opkg-upgrade --hasUpgrade && opkg-upgrade --list | mail -s "opkg-upgrade list $(date '+%Y-%m-%d_%H:%M:%S')" receiver_address@gmail.com 
```
(not so sure about the mail call, not tested)  
  
What this does:
 1. Check if we have upgrades
 2. If yes, send email with the list of upgrades

So, then we need:
 - `--hasUpgrade`: returns 0 only if we have upgrades, used to check if we should email
 - `--list`: only prints the list of updates and exits, used for email contents
  
Having these options would make it possible to do what you want (I think).  
But as mentioned, you would need to configure the mailer yourself and also create the cronjob.  
    
References:
 - https://wiki.openwrt.org/doc/howto/smtp.client
 - https://fixmynix.com/send-mail-command-line-linux-openwrt/
 - https://forum.openwrt.org/viewtopic.php?id=18669
  
Cheers!
Gus

**Comment by tavinus** [comment]
**BIG MAYBE** on sending mails with telnet, like described here:
 - https://mediatemple.net/community/products/dv/204404584/sending-or-viewing-emails-using-telnet

This would increase the complexity of opkg-upgrade quite a lot, but it would be portable and it would not depend on external packages. Not sure if feasible yet though.
  
Also forgot to mention the package `mini-sendmail`, but that has no auth support and seems kind of deprecated (and not available for ChaosCalmer).  
  
I will keep researching, but for now I will probably just implement the two flags mentioned above and let the user do the mailing part.

**Comment by tavinus** [comment]
Hi, I have a working version with the mentioned modes of operation and also the option to use ssmtp directly from opkg-upgrade. You would still need to install and configure the ssmtp package. I had some trouble to make it work with gmail (had no enable unsecure apps, etc), but worked in the end. After you have a working ssmtp config installed, it is as easy as calling:
```
opkg-upgrade -s 'mail@example.com'
```
And the report will be sent to mail@example.com, but only if there are new updates.  
You can force it to always send the e-mail (even when no updates are available) with the `-a flag`, as in:
```
opkg-upgrade -a -s 'mail@example.com'
```
  
I still need to do some more testing and to clean up the code. I was thinking of also having the option to send an HTML e-mail, but maybe I will leave that for a future version.  
  
As mentioned, I have also implemented the `-u, --upgrade-check` and `-l, --list-upgrades` modes, so it is possible to also use those with any mail client with something like:
```
opkg-upgrade -u && opkg-upgrade -l | ssmtp 'mail@example.com'
```
I will see if it is worthy to also implement the other available mailers.  
@txcanyon , do you currently use any mailer already?

**Comment by txcanyon** [comment]
I have ssmtp configured now for using a gmail account I have for my server related emails. I have successfully sent a test message from my LEDE install.

**Comment by tavinus** [comment]
Cool! At least you are using ssmtp with gmail, so this should be a breeze..  
 It was my mother's birthday today so... u know.. had to separate some time to her...

**Comment by tavinus** [comment]
anyways,... I have a cool html email version for ya.
in 1 or 2 days it will be there... (I am a bit drunk to finish it today)

**Comment by tavinus** [comment]
I have done the html email, this is an example of it:
![opkg-list](https://user-images.githubusercontent.com/8039413/27513908-505d44f4-594f-11e7-98df-2580721b341d.PNG)

**Comment by txcanyon** [comment]
Looks great!

**Comment by tavinus** [comment]
@txcanyon , I have pushed `v0.2.0` to the master branch.  
Can you try it please?  
I will make a release after testing a bit more. 
  
Cheers!
Gus

**Comment by txcanyon** [comment]
``root@Router:~# ./opkg-upgrade.sh

Simple OPKG Updater v0.2.0

Done | Updating package lists
Done | Getting upgradable packages list


No packages to install!

Proceed with upgrade? (Y/y to proceed)``

**Comment by tavinus** [comment]
You should never really use the `-e` option with the `-s` option.  
 - `-e` is to print the html message to stdout (if someone wants to use something else than ssmtp)
 - `-s` is to send the e-mail using ssmtp.  

`-e` can also be used to test/see the output of the email without actually sending it.
  
So as I posted above, try using just this:
```
./opkg-upgrade.sh -a -s 'mail@example.com'
```
It should send an email even if there are no updates.  
Instead of the table with packages you will get the message `'No packages to install'`.  
I have just realized that it counts as 1 package though (I'll fix that).
  
And then, are you being asked if you want to continue the upgrade even when sending e-mails?  
Not sure I understand, but I don't get that here...

**Comment by txcanyon** [comment]
Ok understood. Looks like it's working as planned. I just won't see anything until there's an actual update to a package.

The Y/y was just a question if it should be Y/n instead.

**Comment by tavinus** [comment]
Just pushed v0.2.2 with two fixes:
 - Fix to package count on e-mail when there are no updates (was showing 1).
 - Fix to asking to confirm upgrade when no upgrades are available (detection was broken there).
  
You will receive a message with `'No packages to install.'` if using the `-a` option. If you want it to send e-mails only when updates are available, just remove the `-a` option.  
  
About the confirmation message, it works and reads as it says.  
`Y` and `y` will update, anything else will cancel.  
You made me notice that it was asking that even when no updates were available though, fixed.  
  
Cheers!
Gus

**Comment by txcanyon** [comment]
Works great! I made a cronjob for a quick test and it also works.

Thanks for your hard work. I would definitely let LEDE and OpenWrt users know what you've created. I am sure there are lots who would use this as well.

**Comment by tavinus** [comment]
Cool! Thanks for the feedback and suggestions.  
  
I wish there was an easier way to resolve config file conflicts though.  
I may create some functionality for helping with that.  
  
For now I can suggest [this little script](https://gist.github.com/tavinus/07de28617aaac3dcd4ad808f208485f8) for using git diff to compare config files.  
It is a lot better than the `diff` program in `diffutils` and since git is already there, no need for extra packages.  
  
You use it like this:
```
# diff-git /etc/config/dhcp /etc/config/dhcp-opkg
```

Even so, can still be annoying to decide if should merge/discard/migrate to a new config file.

**Comment by txcanyon** [comment]
Just had an update come through. Script works as expected. Nice and neat html table.

I think you can close this enhancement now as a rousing success!

**Comment by tavinus** [comment]
Thx for the feedback.  
Glad it works! :)  
  
Things are a bit busy right now, but I can think of many ways to improve this functionality.  
I am pretty glad on what could be done in a couple of days anyways.  
  
And for people wanting to use other mailers, the option `-e` will print the e-mail so you can pipe it to your mailer (or to a temporary file you can use). If you want to send e-mail only when new updates are available you will need a `-u` check before. To speed things up the second call can include the `-n` parameter, since the package list will be updated on the first call anyways.   
So, it would be something like this:
```
opkg-upgrade -u && opkg-upgrade -n -e | othermailer 'mailer@example.com' 
```
For plain-text e-mails, there is the `-t` flag. Plain text flag works for both `-e` and `-s`.  
  
If by any reason the email string provided is not good for anyone, there is still the option of using the `-l` flag to just list the packages.  
  
thanks @txcanyon for all the ideas and feedback, feel free to post here even though I am closing this.
  
Cheers!
Gus
